//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSVEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要合并到源文件的文件，一般是翻译返回的本地化csv文件
        ///AM是AppendModify的缩写.
        /// </summary>
        internal static string AMFilePathHint {
            get {
                return ResourceManager.GetString("AMFilePathHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSVEditor当前版本已过期，请更新SVN
        ///最新版本({0})
        ///当前版本({1})
        ///
        ///.
        /// </summary>
        internal static string ApplicationRunFailed_LowVersion {
            get {
                return ResourceManager.GetString("ApplicationRunFailed_LowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法打开CSVEditor
        ///出现这个问题可能是以下原因：
        ///■CSVEditor.exe不在SVN目录下
        ///■没有联网
        ///
        ///SVN路径：http://172.16.19.225:81/svn/OrientalSkyServerTables/utilities/CSVEditor/CSVeditor.exe
        ///
        ///如果你无法解决这个问题，请给黄文淼看以下内容：
        ///{0}.
        /// </summary>
        internal static string ApplicationRunFailed_NoVersionFile {
            get {
                return ResourceManager.GetString("ApplicationRunFailed_NoVersionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有检测出文件
        ///{0}
        ///的编码
        ///请注意检查文件内容是否有乱码.
        /// </summary>
        internal static string CharsetDetectorFailedHint {
            get {
                return ResourceManager.GetString("CharsetDetectorFailedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到文件
        ///{0}
        ///的编码是&quot;{1}&quot;
        ///请注意检查文件内容是否有乱码
        ///
        ///如果有乱码，请先尝试用其他软件修改文件的编码
        ///解决不了乱码问题，请找陈天和黄文淼.
        /// </summary>
        internal static string CharsetDetectorNotUTF8Hint {
            get {
                return ResourceManager.GetString("CharsetDetectorNotUTF8Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定要关闭当前的CSV表么？
        ///
        ///请在弹出的Diff软件中，比较文件差异，确认无误后再关闭
        ///如果没有弹出Diff软件，请找黄文淼.
        /// </summary>
        internal static string CloseCSVFormAfterDiffMessageText {
            get {
                return ResourceManager.GetString("CloseCSVFormAfterDiffMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认执行这个操作？.
        /// </summary>
        internal static string ConfirmThisOperation {
            get {
                return ResourceManager.GetString("ConfirmThisOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.4.2
        ///	&quot;查找和替换&quot;窗口在已经打开时按Ctrl+f，把&quot;查找和替换&quot;窗口弹到屏幕最前
        ///
        ///v0.4.1
        ///	修复&quot;查找和替换&quot;、&quot;转到&quot;窗口开启时，保存文件弹出的祥细框不可点的问题
        ///
        ///v0.4.0
        ///	添加CSVEditor启动后检查最新版本，如果当前不是最新版，弹出对话框提示，并退出CSVEditor
        ///	添加本地化校验规则：
        ///		Warning 本地化翻译是两段重复的文本
        ///
        ///v0.3.4
        ///	增加本地化合并工具对&quot;Chinese_Uncensor&quot;列的支持
        ///
        ///v0.3.3
        ///	增加本地化检测规则的Warning：
        ///		填写本地化Key的行，没填写Text
        ///		单元格内容以 ”PLACEHOLDER“开始
        ///	搜索界面，添加没有搜索到时的提示		
        ///	本地化合并工具：添加”合并指定列“功能
        ///
        ///v0.3.2
        ///	修改帮助中的提示文本
        ///
        ///v0.3.1
        ///	添加&quot;打开文件时，检测文件编码&quot;功能
        ///
        ///v0.3.1
        ///	支持打开拖拽到主窗口的文件
        ///
        ///v0.3.0
        ///	添加&quot;插入复制的单元格&quot;功能
        ///	添加校验规则&quot;Plane&quot;
        ///	添加Tortoise的Diff
        ///	这次 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CSVEditor_ChangeNote {
            get {
                return ResourceManager.GetString("CSVEditor_ChangeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个操作会设置csv文件的默认程序为CSV编辑器.
        /// </summary>
        internal static string CSVFileAssociationToolsHint {
            get {
                return ResourceManager.GetString("CSVFileAssociationToolsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM文件中本地化Key包含空格.
        /// </summary>
        internal static string MergeLocalizationToolAMCSVKeyContainsSpaceMessageCaption {
            get {
                return ResourceManager.GetString("MergeLocalizationToolAMCSVKeyContainsSpaceMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key：({0})
        ///
        ///注：
        ///这个错误在AM文件中，并非当前打开的文件
        ///
        ///说明：
        ///请去掉AM文件中本地化Key中的空格后重新运行本地化合并工具
        ///点击本地化合并工具界面右上角的&quot;?&quot;查看提示
        ///本地化表中的Key不应该包含空格
        ///出现这个错误，可能是翻译人员手抖加了空格.
        /// </summary>
        internal static string MergeLocalizationToolAMCSVKeyContainsSpaceMessageText {
            get {
                return ResourceManager.GetString("MergeLocalizationToolAMCSVKeyContainsSpaceMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   源文件：有{0}列
        ///AM文件：有{1}列
        ///
        ///列数不一样，请检查文件正确.
        /// </summary>
        internal static string MergeLocalizationToolColumCountInconformityHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolColumCountInconformityHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM文件和源文件的列头不一致
        ///AM文件第{0}列的列头：({1})
        ///源文件第{0}列的列头：  ({2}).
        /// </summary>
        internal static string MergeLocalizationToolHeadNotSame {
            get {
                return ResourceManager.GetString("MergeLocalizationToolHeadNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 说明：
        ///AM文件会被合并到源文件
        ///
        ///注：
        ///AM文件的表头(第一行)应该和源文件一一对应
        ///例：源文件第3列是&quot;English&quot;，那么AM文件的第三列也应该是&quot;English&quot;
        ///
        ///操作流程：
        ///●检验AM文件
        ///    ○用CSV编辑器打开AM文件
        ///    ○点击顶部菜单栏：布局-&gt;应用校验规则-&gt;本地化
        ///    ○点击顶部菜单栏：工具-&gt;校验当前打开的表
        ///    ○按照提示修改AM文件
        ///●校验源文件，方法同&quot;校验AM文件&quot;
        ///●本地化合并
        ///    ○用CSV编辑器打开源文件
        ///    ○点击顶部菜单栏：工具-&gt;本地化合并
        ///    ○选择AM文件，运行
        ///
        ///合并规则：
        ///●遍历AM文件中的每一行
        ///●获取这行AM数据的AMKey(去除头尾的空白字符)
        ///●如果AMKey为空，跳过这条数据
        ///●在源文件中查找AMKey
        ///    ○源文件中不存在AMKey
        ///          ◆把这行数据插入到源文件结尾
        ///    ○源文件中存在AMKey
        ///          ◆把这行AM数据合并到源文件
        ///          ◆如果AM数据中一个单元格值为空，则跳过这个单元格
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MergeLocalizationToolHelpText {
            get {
                return ResourceManager.GetString("MergeLocalizationToolHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地化合并完成
        ///注意检查文件编码！！！.
        /// </summary>
        internal static string MergeLocalizationToolMergeCompleteHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolMergeCompleteHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择AM文件.
        /// </summary>
        internal static string MergeLocalizationToolNotChooseAMCSVHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolNotChooseAMCSVHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的AM文件不存在.
        /// </summary>
        internal static string MergeLocalizationToolNotExistsAMCSVHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolNotExistsAMCSVHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择的AM文件可能不是本地化文件？
        ///本地化文件：第一行第一个单元格为&quot;String ID&quot;的csv文件.
        /// </summary>
        internal static string MergeLocalizationToolNotLocalizationCSVHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolNotLocalizationCSVHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有选择指定的列.
        /// </summary>
        internal static string MergeLocalizationToolNotSelectMergeColHint {
            get {
                return ResourceManager.GetString("MergeLocalizationToolNotSelectMergeColHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 这个操作会移除表中所有的&apos;\t&apos;，并把&quot;\r\n&quot;替换为&quot;\n&quot;.
        /// </summary>
        internal static string RemoveAllTabAndConvertAllCRLFToLFToolsHint {
            get {
                return ResourceManager.GetString("RemoveAllTabAndConvertAllCRLFToLFToolsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查找：
        ///●“使用通配符时”，使用精准查找
        ///●不“使用通配符时”，使用模糊查找
        ///●通配符：
        ///    ○&apos;*&apos;可以代替任意长度的任意字符
        ///    ○&apos;?&apos;可以代替单个字符
        ///●精准查找：
        ///    ○单元格内容和“查找内容”必须完全匹配
        ///●模糊查找：
        ///    ○单元格内容包含“查找内容”
        ///
        ///替换：
        ///●不区分大小写时，不能替换
        ///●使用通配符时，将查找到的单元格内容替换为“替换为”
        ///●不使用通配符时，只将“查找内容”替换为“替换为”.
        /// </summary>
        internal static string SearchFormWildcardHelpText {
            get {
                return ResourceManager.GetString("SearchFormWildcardHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验规则
        ///
        ///错误：
        ///●单元格包含非法字符(&quot;\t&quot;, &quot;\r\n&quot;)
        ///
        ///警告：
        ///●单元格头尾包含空白字符.
        /// </summary>
        internal static string VerifyDescriptionDefault {
            get {
                return ResourceManager.GetString("VerifyDescriptionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验规则
        ///
        ///错误：
        ///●单元格包含非法字符(&quot;\t&quot;, &quot;\r\n&quot;)
        ///●第一行第一个单元格不是&quot;String ID&quot;
        ///●有重复的Key
        ///
        ///警告：
        ///●(这条警告暂时关闭了)单元格内容头尾包含空白字符
        ///●Key包含空白字符
        ///●Key为空，但是Text不为空
        ///●Text以占位符&quot;PLACEHOLDER&quot;开头
        ///●Text为空，且Key不为空
        ///●Text为两段重复的文本
        ///
        ///消息：
        ///●行内有内容重复的单元格
        ///
        ///名词字典：
        ///Key：本地化表的第一列为本地化Key
        ///Text：本地化表中的翻译，本地化表的第2列到最后一列.
        /// </summary>
        internal static string VerifyDescriptionLocalization {
            get {
                return ResourceManager.GetString("VerifyDescriptionLocalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验规则
        ///
        ///错误：
        ///●单元格包含非法字符(&quot;\t&quot;, &quot;\r\n&quot;)
        ///●PlaneTag列的数值不是由n个两位数字组成(n大于0)
        ///
        ///警告：
        ///●单元格头尾包含空白字符.
        /// </summary>
        internal static string VerifyDescriptionPlane {
            get {
                return ResourceManager.GetString("VerifyDescriptionPlane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格头尾包含空白字符.
        /// </summary>
        internal static string VerifyMessageCaption_HeadAndTailWhiteSpace {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_HeadAndTailWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key不能为空.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_EmptyKey {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_EmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未填写本地化文本.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_EmptyText {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本地化表的第一行第一个单元格应为&quot;String ID&quot;.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_FirstCell {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_FirstCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key不能包含空白字符.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_KeyWhiteSpace {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_KeyWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容包含占位符&quot;PLACEHOLDER&quot;.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_PlaceHolder {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表中包含重复的本地化Key.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_RepeatKey {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_RepeatKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容是两段重复的文本，Key：{0}.
        /// </summary>
        internal static string VerifyMessageCaption_Localization_Special1 {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Localization_Special1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlaneTag必须由n个两位数字组成(n大于0).
        /// </summary>
        internal static string VerifyMessageCaption_Plane_Tag {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_Plane_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行内有内容重复的单元格.
        /// </summary>
        internal static string VerifyMessageCaption_RepeatCellInRow {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_RepeatCellInRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容包含非法字符(&quot;\t&quot;, &quot;\r\n&quot;).
        /// </summary>
        internal static string VerifyMessageCaption_TabOrCRLF {
            get {
                return ResourceManager.GetString("VerifyMessageCaption_TabOrCRLF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容：
        ///({0})
        ///
        ///空白字符由Unicode标准定义
        ///参考Wiki：https://en.wikipedia.org/wiki/Whitespace_character.
        /// </summary>
        internal static string VerifyMessageText_HeadAndTailWhiteSpace {
            get {
                return ResourceManager.GetString("VerifyMessageText_HeadAndTailWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key：
        ///({0})
        ///
        ///Key为空但是Text不为空，代表这行无效。如果不是漏填了Key，就忽略这条警告.
        /// </summary>
        internal static string VerifyMessageText_Localization_EmptyKey {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_EmptyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果是因为本地化的翻译还没返回，请填写占位符&quot;PLACEHOLDER&quot;（注意填大写）.
        /// </summary>
        internal static string VerifyMessageText_Localization_EmptyText {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_EmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当前为({0}).
        /// </summary>
        internal static string VerifyMessageText_Localization_FirstCell {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_FirstCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key：
        ///({0})
        ///
        ///Key包含空白字符，例如空格、换行符等
        ///是不是手抖把下划线&apos;_&apos;打成了空格？.
        /// </summary>
        internal static string VerifyMessageText_Localization_KeyWhiteSpace {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_KeyWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出现“PLACEHOLDER”，可能是因为本地化文本的翻译还没返回，临时占位用的.
        /// </summary>
        internal static string VerifyMessageText_Localization_PlaceHolder {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复的Key:
        ///{0}.
        /// </summary>
        internal static string VerifyMessageText_Localization_RepeatKey {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_RepeatKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容：
        ///({0}).
        /// </summary>
        internal static string VerifyMessageText_Localization_Special1 {
            get {
                return ResourceManager.GetString("VerifyMessageText_Localization_Special1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 例：&quot;000112&quot;、&quot;1112&quot;.
        /// </summary>
        internal static string VerifyMessageText_Plane_Tag {
            get {
                return ResourceManager.GetString("VerifyMessageText_Plane_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复的列:
        ///{0}
        ///怀疑是复制的时候手抖，把一个单元格复制到一行内的多个单元格.
        /// </summary>
        internal static string VerifyMessageText_RepeatCellInRow {
            get {
                return ResourceManager.GetString("VerifyMessageText_RepeatCellInRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单元格内容：
        ///({0})
        ///
        ///运行&quot;移除所有制表符并转换所有换行符&quot;工具可以修复这个错误.
        /// </summary>
        internal static string VerifyMessageText_TabOrCRLF {
            get {
                return ResourceManager.GetString("VerifyMessageText_TabOrCRLF", resourceCulture);
            }
        }
    }
}
